## Basic data extraction

In [1]:
import pickle

def load_pickle(path: str):
    """
    Load and return data from a pickle file.

    Parameters
    ----------
    path : str
        Path to the .pkl file

    Returns
    -------
    Any
        Python object stored in the pickle file
    """
    with open(path, "rb") as f:
        data = pickle.load(f)

    return data

path = "/workspaces/met4a_data/2026_02_12/1770931655.952085.met4a.pkl"
data = load_pickle(path)

In [3]:
type(data)

dict

## Convert pickle dictionary into pandas df

In [4]:
import pandas as pd

def dict_to_df(data: dict) -> pd.DataFrame:
    """
    Convert a dictionary into a pandas DataFrame.

    Supports:
        - dict of lists  -> columns
        - dict of dicts  -> rows
        - list of dicts  -> rows

    Parameters
    ----------
    data : dict
        Dictionary loaded from pickle

    Returns
    -------
    pd.DataFrame
    """
    if isinstance(data, pd.DataFrame):
        return data  # already a dataframe

    # Case 1: dict of lists (most common)
    try:
        return pd.DataFrame(data)
    except Exception:
        pass

    # Case 2: dict of dicts
    try:
        return pd.DataFrame.from_dict(data, orient="index")
    except Exception:
        pass

    raise ValueError("Unsupported dictionary format for DataFrame conversion.")

path = "/workspaces/met4a_data/2026_02_12/1770931655.952085.met4a.pkl"
data = load_pickle(path)
pickle_df = dict_to_df(data)

In [5]:
pickle_df

,start_time,ref_pressure,scale_fac,nsamp,times,pressure,temp,rh
0,1.770932e+09,40.059721,64.0,1000,0.030186,0.000012,4.39,71.8
1,1.770932e+09,40.059721,64.0,1000,0.045316,-0.000017,4.39,71.8
2,1.770932e+09,40.059721,64.0,1000,0.061831,-0.000003,4.39,71.8
3,1.770932e+09,40.059721,64.0,1000,0.078272,-0.000008,4.39,71.8
4,1.770932e+09,40.059721,64.0,1000,0.093379,-0.000056,4.39,71.8
...,...,...,...,...,...,...,...,...
995,1.770932e+09,40.059721,64.0,1000,15.939523,-0.000146,4.58,72.2
996,1.770932e+09,40.059721,64.0,1000,15.956036,-0.000146,4.58,72.2
997,1.770932e+09,40.059721,64.0,1000,15.972389,-0.000220,4.58,72.2
998,1.770932e+09,40.059721,64.0,1000,15.988759,-0.000166,4.58,72.2
999,1.770932e+09,40.059721,64.0,1000,16.003891,-0.000156,4.58,72.2

## Bundle extract from entire directory

In [6]:
from pathlib import Path
import pickle

def load_all_pickles(directory: str | Path) -> list:
    """
    Load all pickle files from a directory into a list.

    Parameters
    ----------
    directory : str | Path
        Path to folder containing .pkl files

    Returns
    -------
    list
        List of objects loaded from pickle files
    """
    directory = Path(directory)

    if not directory.exists():
        raise FileNotFoundError(f"Directory not found: {directory}")

    objects = []

    # Sort so results are deterministic (very helpful for notebooks)
    for pkl_path in sorted(directory.glob("*.pkl")):
        with open(pkl_path, "rb") as f:
            obj = pickle.load(f)
            objects.append(obj)

    return objects

directory_path = "/workspaces/met4a_data/2026_02_12"
data_list = load_all_pickles(directory_path)

In [10]:
import pandas as pd

dfs = [pd.DataFrame(d) for d in data_list]

In [11]:
dfs[0]

,start_time,ref_pressure,scale_fac,nsamp,times,pressure,temp,rh
0,1.770932e+09,40.059721,64.0,1000,0.030186,0.000012,4.39,71.8
1,1.770932e+09,40.059721,64.0,1000,0.045316,-0.000017,4.39,71.8
2,1.770932e+09,40.059721,64.0,1000,0.061831,-0.000003,4.39,71.8
3,1.770932e+09,40.059721,64.0,1000,0.078272,-0.000008,4.39,71.8
4,1.770932e+09,40.059721,64.0,1000,0.093379,-0.000056,4.39,71.8
...,...,...,...,...,...,...,...,...
995,1.770932e+09,40.059721,64.0,1000,15.939523,-0.000146,4.58,72.2
996,1.770932e+09,40.059721,64.0,1000,15.956036,-0.000146,4.58,72.2
997,1.770932e+09,40.059721,64.0,1000,15.972389,-0.000220,4.58,72.2
998,1.770932e+09,40.059721,64.0,1000,15.988759,-0.000166,4.58,72.2
999,1.770932e+09,40.059721,64.0,1000,16.003891,-0.000156,4.58,72.2